export const events = [
  {
    id: 1,
    title: "HackFest 2025",
    category: "Hackathon",
    date: "April 12, 2025",
    time: "9:00 AM",
    venue: "Main Auditorium",
    color: "#1a3aff",
    seats: 200,
    registered: 142,
    description:
      "36 hours of non-stop coding, collaboration, and creativity. Build projects that solve real-world problems. Mentors from top tech companies will guide you through every stage.",
    highlights: ["$10,000 in prizes", "Industry mentors", "Free food & swag", "Team size: 2–5"],
    organizer: "CS Department",
    tags: ["Coding", "Teams", "Prizes"],
  },
  {
    id: 2,
    title: "TechTalks Summit",
    category: "Conference",
    date: "April 18, 2025",
    time: "10:00 AM",
    venue: "Seminar Hall B",
    color: "#0066cc",
    seats: 300,
    registered: 210,
    description:
      "Annual technology conference featuring keynotes, panel discussions, and workshops covering AI, Web3, and Cloud Computing.",
    highlights: ["15+ speakers", "Networking lunch", "Certificate of attendance", "Live Q&A sessions"],
    organizer: "Tech Club",
    tags: ["AI", "Cloud", "Web3"],
  },
  {
    id: 3,
    title: "Designathon",
    category: "Design",
    date: "April 24, 2025",
    time: "11:00 AM",
    venue: "Innovation Lab",
    color: "#6b21a8",
    seats: 80,
    registered: 67,
    description:
      "A 24-hour design sprint where participants create stunning UI/UX prototypes for real-world problems. Judged by industry designers.",
    highlights: ["Figma licenses", "Design kit provided", "Industry judges", "Portfolio boost"],
    organizer: "Design Society",
    tags: ["UI/UX", "Figma", "Design"],
  },
  {
    id: 4,
    title: "CyberSec CTF",
    category: "Competition",
    date: "May 2, 2025",
    time: "8:00 AM",
    venue: "Lab Block 3",
    color: "#0e7c7b",
    seats: 120,
    registered: 55,
    description:
      "Capture The Flag competition testing your cybersecurity skills across forensics, cryptography, web exploitation, and reverse engineering.",
    highlights: ["Solo or pairs", "Beginner track", "Pro track", "Leaderboard prizes"],
    organizer: "InfoSec Club",
    tags: ["Security", "CTF", "Crypto"],
  },
  {
    id: 5,
    title: "Startup Pitch Night",
    category: "Entrepreneurship",
    date: "May 8, 2025",
    time: "5:00 PM",
    venue: "Conference Center",
    color: "#b45309",
    seats: 150,
    registered: 98,
    description:
      "Present your startup idea to a panel of investors and entrepreneurs. Get feedback, mentorship, and potential seed funding.",
    highlights: ["Angel investors panel", "Seed funding opportunity", "Networking dinner", "Media coverage"],
    organizer: "Entrepreneurship Cell",
    tags: ["Startup", "Funding", "Pitch"],
  },
  {
    id: 6,
    title: "AI Workshop Series",
    category: "Workshop",
    date: "May 15, 2025",
    time: "2:00 PM",
    venue: "Smart Classroom 1",
    color: "#1a3aff",
    seats: 60,
    registered: 60,
    description:
      "Hands-on workshop series covering Machine Learning fundamentals, neural networks, and building AI apps with Python and modern frameworks.",
    highlights: ["Hands-on projects", "GPU compute access", "Certificate", "Free resources"],
    organizer: "AI Research Lab",
    tags: ["ML", "Python", "Neural Nets"],
  },
];